name: jamii-tourney-backend
services:
- name: api
  source_dir: /
  github:
    repo: oliverktoo/jtv3
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: VITE_SUPABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: VITE_SUPABASE_ANON_KEY
    scope: RUN_TIME
    type: SECRET
  http_port: 5000